from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import structlog

logger = structlog.get_logger()

FILENAME = "CLAUDE.md"


class ClaudeMdWriter:
    """Writes CLAUDE.md — auto-read by Claude Code CLI from cwd.

    Claude Code reads this file automatically when invoked in the workspace.
    ContextFileManager writes this before ClaudeCodeAdapter is called.
    """

    filename: str = FILENAME

    async def write(
        self,
        workspace_path: str,
        project_id: str,
        current_phase: str = "requirements",
        prd_summary: str = "",
        architecture_summary: str = "",
        key_decisions: list[str] | None = None,
        security_rules: list[str] | None = None,
    ) -> Path:
        decisions = key_decisions or []
        rules = security_rules or []
        decisions_bullets = (
            "\n".join(f"- {d}" for d in decisions) if decisions else "- None yet"
        )
        security_bullets = (
            "\n".join(f"- {r}" for r in rules) if rules else "- None yet"
        )

        content = f"""# forgeSDLC Context for Claude Code
# Project: {project_id} | Phase: {current_phase}
# Auto-generated by forgeSDLC ContextFileManager. Do not edit manually.

## Project Summary
{prd_summary or "Requirements not yet generated."}

## Architecture
{architecture_summary or "Architecture not yet designed."}

## Key Decisions
{decisions_bullets}

## Security Rules
{security_bullets}

## Coding Standards
- All functions must have type hints
- Use `structlog` — never `print()`
- Pydantic v2 for data models — `ConfigDict(strict=True)`
- No bare `except Exception` — catch specific exceptions
- No magic numbers — all constants in `constants.py`
- Max function length: 50 lines | Max file length: 300 lines

## Workflow
- Read AGENTS.md for full project context
- Write files to the workspace path directly
- Report written files with `Wrote file: <path>` format
"""
        path = Path(workspace_path) / FILENAME
        path.write_text(content, encoding="utf-8")
        logger.info("claude_md_writer.written", path=str(path))
        return path