from __future__ import annotations

from pathlib import Path

import structlog

logger = structlog.get_logger()

FILENAME = ".github/copilot-instructions.md"


class CopilotInstructionsWriter:
    """Writes .github/copilot-instructions.md — auto-read by GitHub Copilot.

    GitHub Copilot reads this file from the .github/ directory automatically.
    """

    filename: str = FILENAME

    async def write(
        self,
        workspace_path: str,
        project_id: str,
        current_phase: str = "requirements",
        prd_summary: str = "",
        architecture_summary: str = "",
        key_decisions: list[str] | None = None,
        security_rules: list[str] | None = None,
    ) -> Path:
        decisions = key_decisions or []
        rules = security_rules or []
        decisions_bullets = "\n".join(f"- {d}" for d in decisions) if decisions else "- None yet"
        security_bullets = "\n".join(f"- {r}" for r in rules) if rules else "- None yet"

        content = f"""# GitHub Copilot Instructions
# Project: {project_id} | Phase: {current_phase}
# Auto-generated by forgeSDLC. Do not edit manually.

## Project Context
{prd_summary or "Requirements not yet available."}

## Architecture
{architecture_summary or "Architecture not yet designed."}

## Key Decisions
{decisions_bullets}

## Security Rules
{security_bullets}

## Coding Standards
- Type hints on all functions
- structlog — never print()
- Pydantic v2 models with strict=True
- No bare except — specific exceptions only
- Constants in constants.py — no magic numbers
- ruff for linting
"""
        github_dir = Path(workspace_path) / ".github"
        github_dir.mkdir(parents=True, exist_ok=True)
        path = github_dir / "copilot-instructions.md"
        path.write_text(content, encoding="utf-8")
        logger.info("copilot_instructions_writer.written", path=str(path))
        return path
