from __future__ import annotations

from datetime import UTC, datetime

import structlog
from langchain_core.messages import HumanMessage, SystemMessage

from agents.base_agent import BaseAgent
from interpret.record import InterpretRecord

logger = structlog.get_logger()

# CRITICAL: groq/llama-3.3-70b-versatile — NOT gpt-5.4-mini.
# This is the most commonly confused agent-model assignment in the catalog.
# AGENT_MODELS["agent_9_monitor"] = "groq/llama-3.3-70b-versatile"
# test_agent_9_uses_groq_not_gpt_mini enforces this with two assertions.
_MODEL = "groq/llama-3.3-70b-versatile"


class MonitoringAgent(BaseAgent):
    """Agent 9 — SLO definitions, runbook, on-call playbook, OTel config.

    Model: groq/llama-3.3-70b-versatile (NOT gpt-5.4-mini — regression guard test).
    SLOs extracted from PRD NFR section via keyword matching (zero LLM).
    Runbook generated via groq and written via DiffEngine.
    """

    async def _interpret(
        self,
        packet: object,
        memory_context: object,
        state: dict[str, object],
    ) -> InterpretRecord:
        """Preview monitoring setup. Emits L1 InterpretRecord."""
        deployment_url = str(state.get("deployment_url") or "not deployed yet")

        record = InterpretRecord(
            layer="agent",
            component="MonitoringAgent",
            action=(
                f"MONITORING SETUP\n"
                f"Deployment: {deployment_url}\n"
                f"SLOs: extracted from PRD NFRs (keyword-based, zero LLM)\n"
                f"Output: docs/ops/runbook.md + docs/ops/oncall.md\n"
                f"OTel: opentelemetry-sdk + OTLP exporter config\n"
                f"Model: {_MODEL}"
            ),
            inputs={"deployment_url": deployment_url},
            expected_outputs={
                "slo_definitions": "list[dict]",
                "runbook_path": "str",
            },
            files_it_will_read=[],
            files_it_will_write=["docs/ops/runbook.md", "docs/ops/oncall.md"],
            external_calls=[_MODEL],
            model_selected=_MODEL,  # groq — NOT gpt-5.4-mini
            tool_delegated_to=None,
            reversible=True,
            workspace_files_affected=["docs/ops/runbook.md", "docs/ops/oncall.md"],
            timestamp=datetime.now(tz=UTC),
        )
        logger.info(
            "interpret_record.agent",
            layer=record.layer,
            component="MonitoringAgent",
            deployment_url=deployment_url,
        )
        return record

    async def _execute(
        self,
        state: dict[str, object],
        packet: object,
        memory_context: object,
    ) -> dict[str, object]:
        """Extract SLOs, generate runbook, write monitoring config."""
        prd = str(state.get("prd", ""))
        rfc = str(state.get("rfc", ""))
        deployment_url = state.get("deployment_url")

        # Extract SLOs from PRD NFRs — deterministic, zero LLM
        slos = self._extract_slos(prd)

        # Generate runbook via groq/llama-3.3-70b-versatile via ModelRouter
        adapter = await self.model_router.route(
            agent="agent_9_monitor",  # → groq/llama-3.3-70b-versatile
            task_type="documentation",
            estimated_tokens=int(len(rfc.split()) * 2),
            subscription_tier=str(state.get("subscription_tier", "free")),
            budget_used=float(state.get("budget_used_usd", 0.0) or 0.0),
            budget_total=float(state.get("budget_remaining_usd", 999.0) or 999.0),
        )

        slo_summary = "\n".join(f"- {s['name']}: {s['target']}% / {s['metric']}" for s in slos)
        response = await adapter.ainvoke(  # type: ignore[union-attr]
            [
                SystemMessage(
                    content=(
                        "Generate a production runbook for this service. Include: "
                        "SLO definitions and alert thresholds, on-call escalation path, "
                        "common failure modes and their resolutions, rollback procedure, "
                        "OTel instrumentation setup with OTLP exporter."
                    )
                ),
                HumanMessage(
                    content=(
                        f"Service URL: {deployment_url or 'not deployed'}\n"
                        f"RFC:\n{rfc[:3000]}\n\n"
                        f"SLOs:\n{slo_summary}"
                    )
                ),
            ]
        )

        runbook_content = str(response.content) if response.content else ""
        runbook_with_header = (
            f"<!-- Generated by forgeSDLC Agent 9 — "
            f"{datetime.now(tz=UTC).strftime('%Y-%m-%dT%H:%M:%SZ')} -->\n\n" + runbook_content
        )

        # Write runbook via DiffEngine (L3 InterpretRecord, .forgesdlc.bak)
        workspace_path = "."
        try:
            wctx = await self.workspace.get_context()
            workspace_path = wctx.root_path
        except Exception:
            pass

        import os  # noqa: PLC0415

        runbook_path = os.path.join(workspace_path, "docs", "ops", "runbook.md")
        runbook_diff = await self.diff_engine.generate_diff(
            runbook_path, runbook_with_header, "Agent 9: operations runbook"
        )
        await self.diff_engine.apply_diff(runbook_diff)

        state["monitoring_config"] = {
            "slo_definitions": slos,
            "runbook_path": runbook_path,
            "oncall_path": os.path.join(workspace_path, "docs", "ops", "oncall.md"),
            "provider_used": "groq",
            "otel_configured": True,
            "deployment_url": str(deployment_url) if deployment_url else None,
        }

        logger.info(
            "agent_9.executed",
            slos=len(slos),
            runbook=runbook_path,
        )
        return state

    def _extract_slos(self, prd: str) -> list[dict[str, object]]:
        """Extract SLO candidates from PRD NFR section. Zero LLM — keyword-based."""
        slos: list[dict[str, object]] = []
        prd_lower = prd.lower()

        if "99.9%" in prd_lower or "three nines" in prd_lower:
            slos.append(
                {
                    "name": "Availability",
                    "target": 99.9,
                    "window_hours": 720,
                    "metric": "HTTP 5xx error rate",
                }
            )

        if "200ms" in prd_lower or "< 200" in prd_lower or "p95" in prd_lower:
            slos.append(
                {
                    "name": "Latency P95",
                    "target": 200,
                    "window_hours": 168,
                    "metric": "P95 response time ms",
                }
            )

        if "10,000" in prd_lower or "10000" in prd_lower or "high concurrency" in prd_lower:
            slos.append(
                {
                    "name": "Throughput",
                    "target": 10_000,
                    "window_hours": 24,
                    "metric": "Requests per second",
                }
            )

        if not slos:
            # Default SLO when no explicit NFRs found
            slos.append(
                {
                    "name": "Availability",
                    "target": 99.0,
                    "window_hours": 720,
                    "metric": "HTTP 5xx error rate",
                }
            )

        return slos
