from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import structlog
from langchain_core.messages import HumanMessage, SystemMessage

from agents.base_agent import BaseAgent
from interpret.record import InterpretRecord

logger = structlog.get_logger()

_MODEL = "gpt-5.4-mini"

_STACK_SYSTEM_PROMPT = """\
You are a principal engineer. Recommend a production-ready tech stack.
Structure your response as an Architecture Decision Record (ADR):

# ADR-001: Technology Stack Selection

## Status
Accepted

## Context
[Why this decision was needed]

## Decision
[The chosen stack with justification]

## Technology Choices
- **Language**: [choice + reason]
- **Framework**: [choice + reason]
- **Database**: [choice + reason]
- **ORM/Query**: [choice + reason]
- **API Style**: [REST/GraphQL/gRPC + reason]
- **Testing**: [choice + reason]
- **CI/CD**: [choice + reason]
- **Deployment**: [choice + reason]

## Consequences
### Positive
[Benefits of this stack]

### Negative / Trade-offs
[Drawbacks to be aware of]

## Alternatives Considered
[Other stacks evaluated and why rejected]"""


class TechStackAgent(BaseAgent):
    """Agent 2 — recommends tech stack and writes ADR-001.

    Model: gpt-5.4-mini via ModelRouter
    Memory reads: Layer 4 (preferred stack), Layer 2 (past stack choices)
    Output: state["adr"] populated
            docs/decisions/ADR-001-tech-stack.md written via DiffEngine
            .cursorrules updated with stack-specific coding conventions
    """

    async def _interpret(
        self,
        packet: object,
        memory_context: object,
        state: dict[str, object],
    ) -> InterpretRecord:
        """Preview stack recommendation. Emits L1 InterpretRecord."""
        service_graph = state.get("service_graph") or {}
        arch_type = str(service_graph.get("architecture_type", "monolith"))
        prd_preview = str(state.get("prd", ""))[:100]

        return self._emit_l1_record(
            component="TechStackAgent",
            action=(
                f"Recommending tech stack for {arch_type} "
                f"({str(state.get('user_prompt', ''))[:40]})"
            ),
            inputs={
                "architecture_type": arch_type,
                "prd_preview": prd_preview,
            },
            expected_outputs={
                "adr": "ADR-001 with full stack justification",
                "file": "docs/decisions/ADR-001-tech-stack.md",
            },
            external_calls=[_MODEL],
            model_selected=_MODEL,
            files_write=["docs/decisions/ADR-001-tech-stack.md"],
        )

    async def _execute(
        self,
        state: dict[str, object],
        packet: object,
        memory_context: object,
    ) -> dict[str, object]:
        """Generate ADR-001 and write docs/decisions/ADR-001-tech-stack.md."""
        adapter = await self.model_router.route(
            agent="agent_2_stack",
            task_type="generation",
            estimated_tokens=1_500,
            subscription_tier=str(state.get("subscription_tier", "free")),
            budget_used=float(state.get("budget_used_usd", 0.0) or 0.0),
            budget_total=float(state.get("budget_remaining_usd", 999.0) or 999.0),
        )

        service_graph = state.get("service_graph") or {}
        arch_type = str(service_graph.get("architecture_type", "monolith"))
        services = service_graph.get("services", [])
        prd_summary = str(state.get("prd", ""))[:800]

        prompt = (
            f"Recommend a production-ready tech stack for this project.\n\n"
            f"Project: {state.get('user_prompt', '')}\n"
            f"Architecture: {arch_type}\n"
            f"Services: {services}\n\n"
            f"PRD Summary:\n{prd_summary}\n\n"
            "Write the complete ADR-001 document following the template."
        )

        response = await adapter.ainvoke(
            [
                SystemMessage(content=_STACK_SYSTEM_PROMPT),
                HumanMessage(content=prompt),
            ]
        )

        adr_content = str(response.content) if response.content else ""

        # Add metadata header
        adr_with_header = (
            f"<!-- Generated by forgeSDLC Agent 2 — "
            f"{datetime.now(tz=UTC).strftime('%Y-%m-%dT%H:%M:%SZ')} -->\n\n" + adr_content
        )

        # Write ADR via DiffEngine — emits L3, creates .forgesdlc.bak
        workspace_path = "."
        try:
            wctx = await self.workspace.get_context()
            workspace_path = wctx.root_path
        except Exception:
            pass

        adr_path = str(Path(workspace_path) / "docs" / "decisions" / "ADR-001-tech-stack.md")
        diff = await self.diff_engine.generate_diff(
            filepath=adr_path,
            new_content=adr_with_header,
            reason=f"Agent 2: ADR-001 for {str(state.get('user_prompt', ''))[:50]}",
        )
        await self.diff_engine.apply_diff(diff)

        # Update .cursorrules with stack-specific conventions
        await self._update_cursorrules(adr_content, workspace_path, state)

        state["adr"] = adr_with_header
        logger.info(
            "agent_2.executed",
            adr_chars=len(adr_with_header),
            adr_path=adr_path,
        )
        return state

    async def _update_cursorrules(
        self,
        adr_content: str,
        workspace_path: str,
        state: dict[str, object],
    ) -> None:
        """Update .cursorrules with stack-specific coding conventions."""
        try:
            await self.cfm.write_all(
                project_id=str(state.get("mcp_session_id", "default")),
                workspace_path=workspace_path,
                current_phase="stack_selection",
                prd_summary=str(state.get("prd", ""))[:300],
                architecture_summary=adr_content[:300],
                key_decisions=self._extract_decisions(adr_content),
            )
        except Exception as exc:
            logger.warning("agent_2.cursorrules_update_failed", error=str(exc))

    def _extract_decisions(self, adr_content: str) -> list[str]:
        """Extract key tech decisions from ADR for .cursorrules."""
        decisions: list[str] = []
        for line in adr_content.splitlines():
            line = line.strip()
            if line.startswith("- **") and "**:" in line:
                decisions.append(line.lstrip("- "))
            if len(decisions) >= 5:
                break
        return decisions
