from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import structlog
from langchain_core.messages import HumanMessage, SystemMessage

from agents.base_agent import BaseAgent
from interpret.record import InterpretRecord

logger = structlog.get_logger()

_MODEL = "groq/llama-3.3-70b-specdec"

_PRD_SYSTEM_PROMPT = """\
You are a senior product manager. Generate a comprehensive PRD.
Always include ALL of these sections in this exact order:
1. Executive Summary
2. User Stories
3. Acceptance Criteria
4. Non-Functional Requirements
5. Out of Scope
6. Assumptions and Risks

User Stories format: As a [persona], I want [action], so that [benefit].
Acceptance Criteria format: Given [context], When [action], Then [outcome].
Be specific, measurable, and actionable."""


class RequirementsAgent(BaseAgent):
    """Agent 1 — converts user prompt into structured PRD.

    Model: groq/llama-3.3-70b-specdec (free backbone)
    Memory reads: Layer 1 (similar runs), Layer 4 (user preferences)
    Output: state["prd"] populated, docs/requirements/PRD.md written via DiffEngine
    """

    async def _interpret(
        self,
        packet: object,
        memory_context: object,
        state: dict[str, object],
    ) -> InterpretRecord:
        """Preview PRD structure. Emits L1 InterpretRecord."""
        service_graph = state.get("service_graph") or {}
        arch_type = str(service_graph.get("architecture_type", "monolith"))

        return self._emit_l1_record(
            component="RequirementsAgent",
            action=(
                f"Generating PRD for: {str(state.get('user_prompt', ''))[:60]} "
                f"[{arch_type}]"
            ),
            inputs={
                "user_prompt": state.get("user_prompt", ""),
                "architecture_type": arch_type,
            },
            expected_outputs={
                "prd": "PRD with user stories, AC, NFRs",
                "file": "docs/requirements/PRD.md",
            },
            external_calls=[_MODEL],
            model_selected=_MODEL,
            files_write=["docs/requirements/PRD.md"],
        )

    async def _execute(
        self,
        state: dict[str, object],
        packet: object,
        memory_context: object,
    ) -> dict[str, object]:
        """Generate PRD and write docs/requirements/PRD.md via DiffEngine."""
        adapter = await self.model_router.route(
            agent="agent_1_requirements",
            task_type="generation",
            estimated_tokens=2_000,
            subscription_tier=str(state.get("subscription_tier", "free")),
            budget_used=float(state.get("budget_used_usd", 0.0) or 0.0),
            budget_total=float(state.get("budget_remaining_usd", 999.0) or 999.0),
        )

        service_graph = state.get("service_graph") or {}
        arch_type = str(service_graph.get("architecture_type", "monolith"))
        services = service_graph.get("services", [])

        prompt = (
            f"Generate a complete PRD for the following project.\n\n"
            f"Project: {state.get('user_prompt', '')}\n"
            f"Architecture: {arch_type}\n"
            f"Services: {services}\n\n"
            "Include ALL required sections:\n"
            "# [Project Name] — Product Requirements Document\n"
            "## Executive Summary\n"
            "## User Stories\n"
            "## Acceptance Criteria\n"
            "## Non-Functional Requirements\n"
            "## Out of Scope\n"
            "## Assumptions and Risks"
        )

        response = await adapter.ainvoke(
            [
                SystemMessage(content=_PRD_SYSTEM_PROMPT),
                HumanMessage(content=prompt),
            ]
        )

        prd_content = str(response.content) if response.content else ""

        # Add metadata header
        prd_with_header = (
            f"<!-- Generated by forgeSDLC Agent 1 — "
            f"{datetime.now(tz=timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')} -->\n\n"
            + prd_content
        )

        # Write via DiffEngine — emits L3 InterpretRecord, creates .forgesdlc.bak
        workspace_path = "."
        try:
            wctx = await self.workspace.get_context()
            workspace_path = wctx.root_path
        except Exception:
            pass

        prd_path = str(Path(workspace_path) / "docs" / "requirements" / "PRD.md")
        diff = await self.diff_engine.generate_diff(
            filepath=prd_path,
            new_content=prd_with_header,
            reason=f"Agent 1: PRD for {str(state.get('user_prompt', ''))[:50]}",
        )
        await self.diff_engine.apply_diff(diff)

        state["prd"] = prd_with_header
        logger.info(
            "agent_1.executed",
            prd_chars=len(prd_with_header),
            prd_path=prd_path,
        )
        return state